name: Zuri calendar Deployment

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - develop
      - master
  pull_request:
    branches: 
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd zc_plugin_company_holiday_calendar
            git clean -fd
            git stash
            git pull
            cd calendar_frontend
            yarn install
            yarn build
      
      - name: Deploy backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd zc_plugin_company_holiday_calendar
            git pull
            source venv/bin/activate
            cd calendar_backend
            python3 -m pip install -r requirements.txt
            python3 manage.py makemigrations calendarapp
            python3 manage.py makemigrations db_manager
            python3 manage.py migrate
            python3 manage.py collectstatic --no-input
            pkill -u ${{secrets.USERNAME}} gunicorn
            gunicorn --bind 0.0.0.0:8000 calendar_backend.wsgi --daemon
      
      
